name: Terraform Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Provision Infrastructure with Terraform
    runs-on: ubuntu-latest

    env:
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      TF_VAR_key_name: ${{ secrets.KEY_NAME }}
      TF_VAR_db_password: ${{ secrets.RDS_PASSWORD }}
      TF_VAR_public_key: ${{ secrets.EC2_SSH_KEY }}
      TF_VAR_duckdns_token: ${{ secrets.DUCKDNS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Output EC2 private key
        id: get_key
        run: |
          PRIVATE_KEY=$(terraform output -raw frontend_ec2_private_key)
          echo "$PRIVATE_KEY" > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Upload private key as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ec2-key
          path: ec2-key.pem